# Streamlit Cloud Secrets Configuration
# Add your API keys here when deploying to Streamlit Cloud
# This file should not be committed to version control

[api_keys]
# OpenAI/Google Gemini API Key
GEMINI_API_KEY = "your_gemini_api_key_here"

# Bing Image Search API Key
BING_API_KEY = "your_bing_api_key_here"

# Cloudflare API Key
CLOUDFLARE_API_KEY = "your_cloudflare_api_key_here"

# Google Indexing API Key
GOOGLE_API_KEY = "your_google_api_key_here"

# Pixel API Key
PIXEL_API_KEY = "your_pixel_api_key_here"

[auth]
# Default admin credentials (change these!)
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin123"